### ISSUE TITLE
Add descriptions for Am2900Simple/Strict; rename them to Am2900Teaching/Expert

### ISSUE THREAD

**Issue by Haspamelodica** [Mograsim-Team/Mograsim#6]

**Comment by Haspamelodica** [comment]
If we change the IDs, old projects break. Is this something we can live with? Otherwise, we could leave the IDs the same and mention "teaching" and "expert" only in the description.

**Comment by MaisiKoleni** [comment]
I think this should be ok since there are currently no users apart from us and maybe someone from ls11.

**Comment by Haspamelodica** [comment]
Fixed in 96b4263276150f8966a3d663c2699de3ab02e04e.
